<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add to Favorite</name>
   <tag></tag>
   <elementGuidId>14591270-b6d1-49b5-af8b-f981eb7d0b5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/span/span/span/a/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4935ac13-d90a-4c33-9b47-e29a53b020e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add to Favorite</value>
      <webElementGuid>48d12fa7-f6d8-4edf-9747-ce3381c895dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[1]/span[1]/span[1]/span[1]/a[1]/button[1]</value>
      <webElementGuid>e26e3359-6d0a-4dad-8d08-f04e94128eee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/span/span/span/a/button</value>
      <webElementGuid>ac995050-cce4-45fc-8441-3570fd77055e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Synopsis'])[1]/preceding::button[1]</value>
      <webElementGuid>d45f5c06-31b1-42b6-b7d6-de8e770d2a4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'app', '&quot;', ')/div[1]/div[1]/span[1]/span[1]/span[1]/a[1]/button[1]')])[1]/preceding::button[1]</value>
      <webElementGuid>88c28c57-2fe0-482a-bbe4-969a0ebb6789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add to Favorite']/parent::*</value>
      <webElementGuid>3cb65843-43aa-4b30-83ef-23d2a5bd97bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>e0862123-b125-4407-94f6-c0662d3a11d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Add to Favorite' or . = ' Add to Favorite')]</value>
      <webElementGuid>b606d3b3-4b1b-4727-b553-b21436e14c5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
