<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>127e7360-386a-41a7-b0b8-1510d7d98b65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6e848942-7947-4a25-9711-00e2aa40b05d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.myanimelist.net/images/anime/11/50453.jpg</value>
      <webElementGuid>0fcd3753-d6ea-4d09-87a8-21f835ce89af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[2]/div[@class=&quot;events-cards&quot;]/a[@class=&quot;card&quot;]/div[@class=&quot;event-card&quot;]/img[1]</value>
      <webElementGuid>974254dc-c9c6-4763-81ec-d3c65f51b9bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/a/div/img</value>
      <webElementGuid>798e83e3-d650-4ef3-8150-50f29b51ffbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://cdn.myanimelist.net/images/anime/11/50453.jpg')]</value>
      <webElementGuid>04ac6b85-6ac6-4457-99f4-2de94a4753e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>01ed5813-d04c-4e1b-8dc0-9ce05db8f3c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn.myanimelist.net/images/anime/11/50453.jpg']</value>
      <webElementGuid>0a498ee8-5e77-4bbe-8527-e67f1bd2f88c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
