<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Score012345678910</name>
   <tag></tag>
   <elementGuidId>30b6acc3-739b-4ec9-b6d6-564a3f06d572</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#score</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='score']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b52d4ab2-c9cb-442f-aea6-f6d17334826e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>score</value>
      <webElementGuid>88691e11-503c-4d70-a5ca-938b5649034e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Score012345678910</value>
      <webElementGuid>f6d809d5-eb67-4ac3-ab72-76e2c330f4f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;score&quot;)</value>
      <webElementGuid>9da666da-c4dd-4ee3-8e97-7269d777014a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='score']</value>
      <webElementGuid>29694875-e19b-43c4-8b87-b136a9af1356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/span/span/select</value>
      <webElementGuid>445b4f2c-56db-4324-b380-3311534b6c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Synopsis'])[1]/preceding::select[1]</value>
      <webElementGuid>17637480-3291-46d1-b831-889664903f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'score', '&quot;', ')')])[1]/preceding::select[1]</value>
      <webElementGuid>569fd03e-8eec-4ebb-b5cd-58af467a379d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>21c1fe1e-d9bd-4236-a135-86c4b1cf2b0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'score' and (text() = 'Score012345678910' or . = 'Score012345678910')]</value>
      <webElementGuid>a1f06834-37de-4936-a1ae-df6c46ee0a6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
