<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>9a622ecb-1fc5-4886-87b6-ef6927e06040</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a0111d13-a859-4439-b7e0-e923dd70cf07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.myanimelist.net/images/anime/6/73245.jpg</value>
      <webElementGuid>8d1ded19-1d9b-4f7e-9729-2bbc1fe0a2c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[2]/div[@class=&quot;events-cards&quot;]/a[@class=&quot;card&quot;]/div[@class=&quot;event-card&quot;]/img[1]</value>
      <webElementGuid>18885c25-6325-4705-944e-54ae81d99726</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/a/div/img</value>
      <webElementGuid>8dfe3eff-afbf-4610-bcfc-47dba77c9ece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://cdn.myanimelist.net/images/anime/6/73245.jpg')]</value>
      <webElementGuid>0477c4e1-fffa-4625-9ea9-4002700dab4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>e83cbd31-4cef-47fb-8587-e8947b769016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn.myanimelist.net/images/anime/6/73245.jpg']</value>
      <webElementGuid>d11fdd32-e945-434f-8f64-03f514645799</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
