<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Score012345678910</name>
   <tag></tag>
   <elementGuidId>660121a6-3460-434c-9fec-c25ce59b3a9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#score</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='score']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>95e0a3db-b2a7-400f-a98a-300d2a7bcd97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>score</value>
      <webElementGuid>8ee6a9d1-cd71-4a9b-a40b-cdd35ec8312f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Score012345678910</value>
      <webElementGuid>f67c6bb8-f613-4960-8791-9bf846a1342d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;score&quot;)</value>
      <webElementGuid>918039e0-72d1-47d3-9686-ebde79263fa2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='score']</value>
      <webElementGuid>57776ce4-9737-4def-8bce-008f48421f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/span/span/select</value>
      <webElementGuid>e40836af-a8f8-4659-b22a-6779db2dd554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Synopsis'])[1]/preceding::select[1]</value>
      <webElementGuid>46ab3659-b769-4076-a469-363de7c494f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'app', '&quot;', ')/div[1]/div[1]/p[3]')])[1]/preceding::select[1]</value>
      <webElementGuid>9cb849ad-613a-4e1d-98ff-983681718a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>b491f9e5-d6c2-47f6-b17d-607d7ff1dc32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'score' and (text() = 'Score012345678910' or . = 'Score012345678910')]</value>
      <webElementGuid>dada50b8-803f-4198-bf90-f4ef22be0e8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
