<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_naruto</name>
   <tag></tag>
   <elementGuidId>405d261a-a6a1-43d0-905a-ba1e0106d006</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.text_error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div/h2[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>102a083a-89c6-4cf4-8d47-9accfc7ca10a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_error</value>
      <webElementGuid>85c74932-52db-4bdf-8393-9a51ab7dc95c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>naruto</value>
      <webElementGuid>d1b5bb02-66c5-46c6-942d-5a2e8f4cd82e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[2]/div[1]/h2[2]/i[@class=&quot;text_error&quot;]</value>
      <webElementGuid>5ff7f1bd-dfab-4c41-a03c-6d672b86fc41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/h2[2]/i</value>
      <webElementGuid>2c20fee5-3789-4a0e-bfb0-d141b3ee196d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error! not found'])[1]/following::i[1]</value>
      <webElementGuid>349ee172-7980-4ee3-b147-8b85059ed30c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='naruto']/parent::*</value>
      <webElementGuid>7b70bc2a-eb7e-4b2d-8313-330b9845b1cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>96728562-2e9f-47c2-8073-c067be4840e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'naruto' or . = 'naruto')]</value>
      <webElementGuid>f4a15600-6b6a-4613-b779-528cd57739e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
