<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Log out_search-field</name>
   <tag></tag>
   <elementGuidId>f4238251-b11d-4c30-ada3-cdbb5475e6e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.search-field</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>705c2db0-5a59-42ea-872f-7b581233bdce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>dee1e35d-2b52-4dfe-ba67-37d3d1f3288a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-field</value>
      <webElementGuid>3d2960f7-ea23-40a5-a10d-609bbc009943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search for title:</value>
      <webElementGuid>9e9ff485-9e67-4018-9e0d-9e3d440d2ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;events&quot;]/form[@class=&quot;search-box&quot;]/input[@class=&quot;search-field&quot;]</value>
      <webElementGuid>ade83770-1a2c-4f74-83da-80406e4aaaa3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='search']</value>
      <webElementGuid>ea1b1e11-ac55-43b8-a6e7-018fbe0fe568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/form/input</value>
      <webElementGuid>783d1593-2f95-4017-8806-123324f5a8d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d36e3bb9-3e3a-445e-b4b0-b61ee6692dd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @placeholder = 'Search for title:']</value>
      <webElementGuid>24f9750b-9214-4088-9ff8-3bd9e6fdbea4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
